import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { cancelSalesOrder, listSalesOrders } from './sales.api';
import type { SalesOrderFilters, SalesOrderListItem } from './sales.types';

export function SalesOrderListPage() {
  const [filters, setFilters] = useState<SalesOrderFilters>({ status: 'all', paymentStatus: 'all' });
  const [orders, setOrders] = useState<SalesOrderListItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  async function load() { setLoading(true); setError(null); try { setOrders(await listSalesOrders(filters)); } catch (cause) { setError(cause instanceof Error ? cause.message : '订单加载失败'); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [filters]);
  async function cancel(order: SalesOrderListItem) { try { await cancelSalesOrder(order.id); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : '取消失败'); } }
  return <section className="feature-page"><div className="screen-head"><div><p className="eyebrow">销售管理</p><h1>销售订单</h1><p>新建订单时可以选择客户或散客，确认后等待出库。</p></div><Link className="btn-primary" to="/sales/new">新建订单</Link></div><div className="toolbar"><input className="search-input" placeholder="搜索订单号或客户" aria-label="搜索销售订单" value={filters.query ?? ''} onChange={(event) => setFilters((current) => ({ ...current, query: event.target.value }))} /><select className="filter-select" aria-label="订单状态" value={filters.status ?? 'all'} onChange={(event) => setFilters((current) => ({ ...current, status: event.target.value as SalesOrderFilters['status'] }))}><option value="all">全部状态</option><option value="draft">草稿</option><option value="pending_shipment">待出库</option><option value="completed">已完成</option><option value="cancelled">已取消</option></select><select className="filter-select" aria-label="收款状态" value={filters.paymentStatus ?? 'all'} onChange={(event) => setFilters((current) => ({ ...current, paymentStatus: event.target.value as SalesOrderFilters['paymentStatus'] }))}><option value="all">全部收款</option><option value="unpaid">未收款</option><option value="paid">已收款</option></select><input className="filter-select" type="date" aria-label="订单日期" value={filters.date ?? ''} onChange={(event) => setFilters((current) => ({ ...current, date: event.target.value || undefined }))} /></div>{error && <p className="form-error" role="alert">{error}</p>}<div className="table-panel"><table><thead><tr><th>订单号</th><th>客户</th><th>金额</th><th>状态</th><th>收款</th><th>操作</th></tr></thead><tbody>{loading ? <tr><td colSpan={6}>加载中…</td></tr> : orders.length === 0 ? <tr><td colSpan={6}>暂无销售订单</td></tr> : orders.map((order) => <tr key={order.id}><td><Link to={order.status === 'draft' ? `/sales/${order.id}` : `/sales/${order.id}/detail`}>{order.orderNo}</Link></td><td>{order.customerName}</td><td>¥{order.totalAmount.toFixed(2)}</td><td>{order.status === 'draft' ? '草稿' : order.status === 'pending_shipment' ? '待出库' : order.status === 'completed' ? '已完成' : '已取消'}</td><td>{order.paymentStatus === 'paid' ? '已收款' : '未收款'}</td><td>{(order.status === 'draft' || order.status === 'pending_shipment') && <button className="text-button" type="button" onClick={() => void cancel(order)}>取消</button>}</td></tr>)}</tbody></table></div></section>;
}
