import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { getSalesOrder, markSalesOrderPaid, revertSalesOrderPayment, shipSalesOrder } from './sales.api';
import type { PaymentMethod, SalesOrderDetail } from './sales.types';

export function SalesOrderDetailPage({ orderId, role }: { orderId: string; role: 'owner' | 'staff' }) {
  const [order, setOrder] = useState<SalesOrderDetail | null>(null);
  const [method, setMethod] = useState<PaymentMethod>('wechat');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  async function load() { try { setOrder(await getSalesOrder(orderId)); } catch (cause) { setError(cause instanceof Error ? cause.message : '订单加载失败'); } }
  useEffect(() => { void load(); }, [orderId]);
  async function ship() { setBusy(true); setError(null); try { await shipSalesOrder(orderId); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : '出库失败'); await load(); } finally { setBusy(false); } }
  async function markPaid() { setBusy(true); setError(null); try { await markSalesOrderPaid(orderId, method); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : '收款失败'); } finally { setBusy(false); } }
  async function revertPayment() { setBusy(true); setError(null); try { await revertSalesOrderPayment(orderId); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : '撤销失败'); } finally { setBusy(false); } }
  if (!order) return <section className="feature-page"><p className="form-hint">加载中…</p>{error && <p className="form-error" role="alert">{error}</p>}</section>;
  const statusLabel = order.status === 'pending_shipment' ? '待出库' : order.status === 'completed' ? '已完成' : order.status === 'cancelled' ? '已取消' : '草稿';
  return <section className="feature-page"><div className="screen-head"><div><p className="eyebrow">销售订单</p><h1>{order.orderNo}</h1><p>客户：{order.customerName} · 金额：¥{order.totalAmount.toFixed(2)}{order.refundedAmount ? ` · 已退款 ¥${order.refundedAmount.toFixed(2)}` : ''}</p></div><span className="status-pill">{statusLabel}</span></div><div className="table-panel"><table><thead><tr><th>玩具</th><th>SKU</th><th>售价</th><th>数量</th><th>已售后</th><th>小计</th></tr></thead><tbody>{order.items.map((item) => <tr key={item.productId}><td>{item.productName}</td><td>{item.sku}</td><td>¥{item.unitPrice.toFixed(2)}</td><td>{item.quantity}</td><td>{item.handledQuantity ?? 0}</td><td>¥{(item.unitPrice * item.quantity).toFixed(2)}</td></tr>)}</tbody></table></div>{error && <p className="form-error" role="alert">{error}</p>}<div className="drawer-actions">{order.status === 'pending_shipment' && <button className="btn-primary" type="button" disabled={busy} onClick={() => void ship()}>{busy ? '处理中…' : '确认出库'}</button>}{order.status === 'completed' && order.items.some((item) => (item.handledQuantity ?? 0) < item.quantity) && <Link className="btn-secondary" to={`/sales/${order.id}/after-sales`}>办理售后</Link>}{order.status === 'completed' && order.paymentStatus === 'unpaid' && <><select aria-label="付款方式" value={method} onChange={(event) => setMethod(event.target.value as PaymentMethod)}><option value="wechat">微信</option><option value="alipay">支付宝</option><option value="cash">现金</option><option value="other">其他</option></select><button className="btn-primary" type="button" disabled={busy} onClick={() => void markPaid()}>标记已收款{order.netAmount !== undefined && order.netAmount !== order.totalAmount ? ` ¥${order.netAmount.toFixed(2)}` : ''}</button></>}{order.status === 'completed' && order.paymentStatus === 'paid' && <span className="status-pill">已收款</span>}{role === 'owner' && order.status === 'completed' && order.paymentStatus === 'paid' && <button className="btn-secondary" type="button" disabled={busy} onClick={() => void revertPayment()}>撤销收款</button>}</div></section>;
}
