import {toAppError} from '../../lib/app-error';import type{Json}from'../../lib/database.types';import{supabase}from'../../lib/supabase';import type{AdjustmentType,InventoryItem,StockCountDetail}from'./inventory.types';
export async function listInventory(query='',alertOnly=false):Promise<InventoryItem[]>{const{data,error}=await supabase.rpc('list_inventory',{p_query:query.trim(),p_alert_only:alertOnly});if(error)throw toAppError(error);return(data??[]).map(r=>({id:r.id,sku:r.sku,barcode:r.barcode,name:r.name,category:r.category,stockQty:r.stock_qty,lowStockThreshold:r.low_stock_threshold,status:r.status}));}
export async function createStockCount(remark=''){const{data,error}=await supabase.rpc('create_stock_count',{p_remark:remark.trim()||null});if(error)throw toAppError(error);return String(data)}
export async function getStockCount(id:string){const{data,error}=await supabase.rpc('get_stock_count',{p_id:id});if(error)throw toAppError(error);return data as unknown as StockCountDetail}
export async function saveStockCountDraft(id:string,items:{itemId:string;actualQuantity:number}[]){const{error}=await supabase.rpc('save_stock_count_draft',{p_stock_count_id:id,p_items:items as Json});if(error)throw toAppError(error)}
export async function confirmStockCount(id:string,requestId:string){const{data,error}=await supabase.rpc('confirm_stock_count',{p_stock_count_id:id,p_request_id:requestId});if(error)throw toAppError(error);return String(data)}
export async function cancelStockCount(id:string){const{error}=await supabase.rpc('cancel_stock_count',{p_stock_count_id:id});if(error)throw toAppError(error)}
export async function postStockAdjustment(input:{requestId:string;type:AdjustmentType;reason:string;items:{productId:string;quantityDelta:number}[]}){const{data,error}=await supabase.rpc('post_stock_adjustment',{p_request_id:input.requestId,p_type:input.type,p_reason:input.reason.trim(),p_items:input.items as Json});if(error)throw toAppError(error);return String(data)}
export async function listStockCounts(){const{data,error}=await supabase.rpc('list_stock_counts',{p_query:'',p_status:null,p_date:null});if(error)throw toAppError(error);return data??[]}
export async function listStockAdjustments(){const{data,error}=await supabase.rpc('list_stock_adjustments',{p_query:'',p_type:null,p_date:null});if(error)throw toAppError(error);return data??[]}
